default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Sevastopol123!
  host: localhost
  port: 5433

development:
  <<: *default
  database: master1_development

test:
  <<: *default
  database: master1_test

production:
  <<: *default
  database: master1_production
  username: postgres
  password: <%= ENV["MASTER1_DATABASE_PASSWORD"] %>
