default: &default
  adapter: postgresql
  encoding: unicode
  # Настройки пула соединений
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vineyard_user
  password: 1029
  host: localhost

development:
  <<: *default
  database: vineyard_monitoring_development

test:
  <<: *default
  database: vineyard_monitoring_test

production:
  <<: *default
  database: vineyard_monitoring_production
  username: vineyard_user
  password: <%= ENV["VINEYARD_DATABASE_PASSWORD"] %>