const VIEW_TRANSITION_MS = 900;
const EXIT_PANELS_MS = VIEW_TRANSITION_MS;
const DESKTOP_SWITCH_EASE = 'cubic-bezier(0.16, 1, 0.3, 1)';
const FIRST_WAYPOINT_TRANSIT_THRESHOLD_M = 10;
const ROUTE_ZONE_REJECT_LOG_COOLDOWN_MS = 1200;
const TEMPLATE_ROUTE_REJECT_COOLDOWN_MS = 1200;
const TELEMETRY_SEND_EVERY_MS = 1000;
const ZONE_COLORS_STORAGE_KEY = 'zone_colors_v1';

const VIDEO_CANVAS_WIDTH = 640;
const VIDEO_CANVAS_HEIGHT = 360;
const VIDEO_RECORDING_FPS = 15;
const VIDEO_BACKEND_CONTENT_TYPE = 'video/webm';
const VIDEO_RECORDER_MIME_CANDIDATES = ['video/webm;codecs=vp8', 'video/webm'];
const VIDEO_MULTIPART_CHUNK_SIZE_BYTES = 1024 * 1024;
const AI_RESULTS_POLL_INTERVAL_MS = 5000;
const LOGS_CLEARED_AT_KEY = 'ui_logs_cleared_at_ms_v1';

export {
VIEW_TRANSITION_MS,
EXIT_PANELS_MS,
DESKTOP_SWITCH_EASE,
FIRST_WAYPOINT_TRANSIT_THRESHOLD_M,
ROUTE_ZONE_REJECT_LOG_COOLDOWN_MS,
TEMPLATE_ROUTE_REJECT_COOLDOWN_MS,
TELEMETRY_SEND_EVERY_MS,
ZONE_COLORS_STORAGE_KEY,
VIDEO_CANVAS_WIDTH,
VIDEO_CANVAS_HEIGHT,
VIDEO_RECORDING_FPS,
VIDEO_BACKEND_CONTENT_TYPE,
VIDEO_RECORDER_MIME_CANDIDATES,
VIDEO_MULTIPART_CHUNK_SIZE_BYTES,
AI_RESULTS_POLL_INTERVAL_MS,
LOGS_CLEARED_AT_KEY,
};
