default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DB_POOL", 5).to_i %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "vineyard_app") %>
  username: <%= ENV.fetch("DB_USERNAME", "vineyard_user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "1029") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_TEST_NAME", "vineyard_app_test") %>
  username: <%= ENV.fetch("DB_USERNAME", "vineyard_user") %>
  password: <%= ENV.fetch("DB_PASSWORD", "1029") %>
  host: <%= ENV.fetch("DB_HOST", "localhost") %>

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV.fetch("DB_NAME", "vineyard_app_production") %>
    username: <%= ENV.fetch("DB_USERNAME", "vineyard_user") %>
    password: <%= ENV.fetch("DB_PASSWORD", "build_dummy") %>
    host: <%= ENV.fetch("DB_HOST", "postgres") %>
  cache:
    <<: *primary_production
    database: <%= ENV.fetch("DB_CACHE_NAME", "#{ENV.fetch('DB_NAME', 'vineyard_app_production')}_cache") %>
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV.fetch("DB_QUEUE_NAME", "#{ENV.fetch('DB_NAME', 'vineyard_app_production')}_queue") %>
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV.fetch("DB_CABLE_NAME", "#{ENV.fetch('DB_NAME', 'vineyard_app_production')}_cable") %>
    migrations_paths: db/cable_migrate
